'use client';
import {useEffect,useMemo,useState} from 'react';
import {BarChart3,RefreshCw} from 'lucide-react';
const n=(v:number,d=1)=>Number.isFinite(v)?v.toFixed(d):'—';
const session=(ts:number)=>{const h=new Date(ts).getUTCHours();if(h>=6&&h<13)return 'London';if(h>=13&&h<21)return 'New York';return 'Asia';};
function stats(rows:any[]){const c=rows.filter(x=>x.status==='closed'&&Number.isFinite(Number(x.resultR))),w=c.filter(x=>Number(x.resultR)>0),loss=c.filter(x=>Number(x.resultR)<=0),gp=w.reduce((s,x)=>s+Number(x.resultR),0),gl=Math.abs(loss.reduce((s,x)=>s+Number(x.resultR),0)),net=c.reduce((s,x)=>s+Number(x.resultR),0);return {trades:c.length,win:c.length?100*w.length/c.length:0,pf:gl?gp/gl:null,net,avg:c.length?net/c.length:0};}
export default function PerformanceCenter(){const [rows,setRows]=useState<any[]>([]),[mode,setMode]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);const load=async()=>{setBusy(true);setError('');try{const r=await fetch('/api/journal?limit=500',{cache:'no-store'}),j=await r.json();if(!r.ok||!j.ok)throw Error(j?.message||'السجل يحتاج تسجيل دخول ChatGPT.');setRows(j.entries||[]);setMode(j.mode||'');}catch(e){try{const local=JSON.parse(localStorage.getItem('gold-paper-trades')||'[]');if(Array.isArray(local)){setRows(local.map((x:any)=>({id:x.id,kind:'paper_trade',createdAt:x.openedAt,updatedAt:x.closedAt||x.openedAt,side:x.side,entry:x.entry,sl:x.sl,tp:x.tp,exit:x.exit,resultR:x.resultR,score:x.score,regime:x.regime,status:x.status,metadata:{mode:x.mode||'standard',eventName:x.eventName||null}})));setMode('browser-local');setError('');return;}}catch{}setError(e instanceof Error?e.message:'تعذر قراءة الأداء.');}finally{setBusy(false);}};useEffect(()=>{void load();},[]);
 const paper=useMemo(()=>rows.filter(x=>x.kind==='paper_trade'),[rows]),closed=paper.filter(x=>x.status==='closed'),overall=stats(closed),news=stats(closed.filter(x=>x.metadata?.mode==='news')),standard=stats(closed.filter(x=>x.metadata?.mode!=='news'));
 const windows=[20,50,100].map(k=>[k,stats(closed.slice(0,k))] as const),regimes=Object.entries(closed.reduce((a:any,x:any)=>{const k=x.regime||'unknown';(a[k]??=[]).push(x);return a;},{})).sort((a:any,b:any)=>b[1].length-a[1].length).slice(0,5),sessions=['London','New York','Asia'].map(s=>[s,stats(closed.filter(x=>session(Number(x.createdAt))===s))] as const);
 return <><section className="panel"><div className="panelhead"><div><span className="eyebrow">PERFORMANCE CENTER</span><h2>الأداء الحقيقي المسجل</h2></div><button className="iconbutton" onClick={load} disabled={busy}><RefreshCw size={16}/>{busy?'تحديث':'تحديث'}</button></div><p className="muted">يعتمد على Trade Journal وليس على درجة التوافق. افصل دائمًا NEWS MODE عن الصفقات الفنية العادية.</p>{error&&<div className="warning">{error}</div>}<div className="labstats big"><span>Trades <b>{overall.trades}</b></span><span>Win Rate <b>{n(overall.win)}%</b></span><span>Profit Factor <b>{overall.pf==null?'—':n(overall.pf,2)}</b></span><span>Net <b>{n(overall.net,2)}R</b></span><span>Avg <b>{n(overall.avg,3)}R</b></span><span>Storage <b>{mode||'—'}</b></span></div></section>
 <div className="grid"><section className="panel"><h3>NEWS vs Standard</h3>{[['NEWS MODE',news],['STANDARD',standard]].map(([k,v]:any)=><article className="papertrade" key={k}><div><strong>{k}</strong><small>{v.trades} صفقة · Win {n(v.win)}%</small></div><span className={v.net>0?'connected':'offline'}>{v.net>0?'+':''}{n(v.net,2)}R</span></article>)}</section><section className="panel"><h3>آخر 20 / 50 / 100</h3>{windows.map(([k,v])=><article className="papertrade" key={k}><div><strong>آخر {k}</strong><small>{v.trades} صفقة · PF {v.pf==null?'—':n(v.pf,2)}</small></div><span>{n(v.win)}% · {n(v.net,2)}R</span></article>)}</section></div>
 <div className="grid"><section className="panel"><h3>حسب الجلسة</h3>{sessions.map(([k,v])=><article className="papertrade" key={k}><div><strong>{k}</strong><small>{v.trades} صفقة</small></div><span>{n(v.win)}% · {n(v.net,2)}R</span></article>)}</section><section className="panel"><h3>حسب Market Regime</h3>{regimes.length?regimes.map(([k,r]:any)=>{const v=stats(r);return <article className="papertrade" key={k}><div><strong>{k}</strong><small>{v.trades} صفقة</small></div><span>{n(v.win)}% · {n(v.net,2)}R</span></article>}):<p className="muted">لا توجد نتائج كافية بعد.</p>}</section></div></>}