'use client';
import {useEffect,useMemo,useState} from 'react';
import {Activity,Database,FlaskConical,Play,ShieldCheck,Trash2,TriangleAlert} from 'lucide-react';
import type {Candle,MarketRegime,Rules} from '../lib/engine';

type Signal={id:string;mode?:'standard'|'news';eventName?:string;sideCode:'buy'|'sell';side:string;entry:number;sl:number;tp:number;score:number;rr:number;time:number};
type PaperTrade={id:string;signalId:string;mode?:'standard'|'news';eventName?:string;side:'buy'|'sell';entry:number;sl:number;tp:number;openedAt:number;closedAt?:number;exit?:number;resultR?:number;score:number;regime:string;status:'open'|'closed';kind?:string;createdAt?:number;updatedAt?:number};
type Fold={trainFrom:number;trainTo:number;testFrom:number;testTo:number;selectedRules:{minScore:number;adx:number;spike:number};train:{trades:number;expectancyR:number;maxDrawdownR:number};test:{trades:number;winRate:number;profitFactor:number|null;expectancyR:number;netR:number;maxDrawdownR:number}};
type Backtest={strategyVersion:string;costs:{spreadUsd:number;slippageUsd:number};history:{chunks:number;candles:number;from:number|null;to:number|null};result:{trades:number;wins:number;losses:number;winRate:number;profitFactor:number|null;expectancyR:number;netR:number;maxDrawdownR:number;from:number|null;to:number|null;sampleCandles:number;assumptions:string[];recent:any[]};walkForward:{folds:Fold[];outOfSampleTrades:number;outOfSampleWinRate:number;outOfSampleProfitFactor:number|null;outOfSampleExpectancyR:number;outOfSampleNetR:number;outOfSampleMaxDrawdownR:number;positiveFolds:number;stabilityScore:number;notes:string[]}};
const num=(v:number|null|undefined,d=2)=>v==null||!Number.isFinite(v)?'—':v.toLocaleString('en-US',{maximumFractionDigits:d,minimumFractionDigits:d});
const dt=(v:number|null|undefined)=>v?new Date(v).toLocaleString('ar-AE',{timeZone:'Asia/Dubai',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}):'—';

export default function StrategyLab({signal,regime,quotePrice,quoteLive,latestM1,rules}:{signal:Signal|null;regime?:MarketRegime|null;quotePrice?:number|null;quoteLive:boolean;latestM1?:Candle|null;rules:Rules}){
  const [paper,setPaper]=useState(false),[trades,setTrades]=useState<PaperTrade[]>([]),[journalMode,setJournalMode]=useState('loading'),[backtest,setBacktest]=useState<Backtest|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const cache=(next:PaperTrade[])=>{try{localStorage.setItem('gold-paper-trades',JSON.stringify(next.slice(0,200)));}catch{}};
  const persist=async(t:PaperTrade)=>{try{const r=await fetch('/api/journal',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:t.id,kind:'paper_trade',signalId:t.signalId,side:t.side,entry:t.entry,sl:t.sl,tp:t.tp,exit:t.exit,resultR:t.resultR,score:t.score,regime:t.regime,status:t.status,createdAt:t.openedAt,metadata:{closedAt:t.closedAt??null,mode:t.mode||'standard',eventName:t.eventName||null}})}),j=await r.json();if(r.ok&&j?.ok)setJournalMode(j.mode==='d1'?'D1 server':'Server memory');}catch{setJournalMode('local fallback');}};
  useEffect(()=>{(async()=>{try{setPaper(localStorage.getItem('gold-paper-enabled')==='true');const r=await fetch('/api/journal?kind=paper_trade&limit=200',{cache:'no-store'}),j=await r.json();if(r.ok&&j?.ok&&Array.isArray(j.entries)){const rows=j.entries.map((x:any):PaperTrade=>({id:String(x.id),signalId:String(x.signalId||''),side:x.side==='sell'?'sell':'buy',entry:Number(x.entry),sl:Number(x.sl),tp:Number(x.tp),openedAt:Number(x.createdAt),closedAt:Number(x.metadata?.closedAt||0)||undefined,exit:x.exit==null?undefined:Number(x.exit),resultR:x.resultR==null?undefined:Number(x.resultR),score:Number(x.score||0),regime:String(x.regime||'غير محسوم'),status:x.status==='closed'?'closed':'open',mode:x.metadata?.mode==='news'?'news':'standard',eventName:x.metadata?.eventName?String(x.metadata.eventName):undefined}));setTrades(rows);cache(rows);setJournalMode(j.mode==='d1'?'D1 server':'Server memory');return;}}catch{}try{const local=JSON.parse(localStorage.getItem('gold-paper-trades')||'[]');if(Array.isArray(local))setTrades(local.slice(0,200));}catch{}setJournalMode('local fallback');})();},[]);
  const save=(next:PaperTrade[],changed?:PaperTrade)=>{setTrades(next);cache(next);if(changed)void persist(changed);};
  const toggle=()=>{const v=!paper;setPaper(v);try{localStorage.setItem('gold-paper-enabled',String(v));}catch{}};
  useEffect(()=>{
    if(!paper||!signal||!quoteLive)return;
    if(trades.some(t=>t.signalId===signal.id)||trades.some(t=>t.status==='open'))return;
    const px=Number.isFinite(Number(quotePrice))?Number(quotePrice):signal.entry,slDist=Math.abs(signal.entry-signal.sl),tpDist=Math.abs(signal.tp-signal.entry),buy=signal.sideCode==='buy';
    const t:PaperTrade={id:signal.id+':'+Date.now(),signalId:signal.id,mode:signal.mode||'standard',eventName:signal.eventName,side:signal.sideCode,entry:px,sl:buy?px-slDist:px+slDist,tp:buy?px+tpDist:px-tpDist,openedAt:Date.now(),score:signal.score,regime:regime?.label||'غير محسوم',status:'open'};save([t,...trades],t);
  },[paper,signal?.id,quoteLive]);
  useEffect(()=>{
    const open=trades.find(t=>t.status==='open');if(!open)return;const buy=open.side==='buy',risk=Math.abs(open.entry-open.sl);if(!risk)return;
    let exit:number|undefined,resultR:number|undefined,when=Date.now();
    if(Number.isFinite(Number(quotePrice))){const q=Number(quotePrice);if((buy&&q<=open.sl)||(!buy&&q>=open.sl)){exit=open.sl;resultR=-1;}else if((buy&&q>=open.tp)||(!buy&&q<=open.tp)){exit=open.tp;resultR=Math.abs(open.tp-open.entry)/risk;}}
    const firstFullMinute=Math.floor(open.openedAt/60000)*60000+60000;
    if(exit==null&&latestM1&&latestM1.time>=firstFullMinute){const stop=buy?latestM1.low<=open.sl:latestM1.high>=open.sl,target=buy?latestM1.high>=open.tp:latestM1.low<=open.tp;if(stop){exit=open.sl;resultR=-1;when=latestM1.time+60000;}else if(target){exit=open.tp;resultR=Math.abs(open.tp-open.entry)/risk;when=latestM1.time+60000;}}
    if(exit!=null&&resultR!=null){const closed={...open,status:'closed' as const,exit,closedAt:when,resultR},next=trades.map(t=>t.id===open.id?closed:t);save(next,closed);}
  },[quotePrice,latestM1?.time]);
  const stats=useMemo(()=>{const closed=trades.filter(t=>t.status==='closed'&&Number.isFinite(t.resultR)),wins=closed.filter(t=>(t.resultR||0)>0).length,net=closed.reduce((s,t)=>s+(t.resultR||0),0);return {closed:closed.length,wins,losses:closed.length-wins,winRate:closed.length?100*wins/closed.length:0,net};},[trades]);
  const runBacktest=async()=>{setBusy(true);setError('');try{const qs=new URLSearchParams({minScore:String(rules.minScore),adx:String(rules.adx),spike:String(rules.spike),chunks:'5',spread:'.45',slippage:'.12'}),r=await fetch('/api/backtest?'+qs.toString(),{cache:'no-store'}),j=await r.json();if(!r.ok||!j?.ok)throw Error(j?.message||'تعذر الاختبار');setBacktest(j);}catch(e){setError(e instanceof Error?e.message:'تعذر الاختبار التاريخي.');}finally{setBusy(false);}};
  return <>
    <section className="panel labhero"><div className="panelhead"><div><span className="eyebrow">STRATEGY LAB 3.0</span><h2>مختبر الاستراتيجية والمخاطر</h2></div><FlaskConical/></div><p className="muted">يقيس الأداء بدل تخمينه: Paper Trading محفوظ على الخادم عند توفر التخزين، Backtest عميق بتكلفة تنفيذ افتراضية، وWalk‑Forward يقيس فترات لم تدخل في اختيار الإعدادات. الأرقام ليست ضماناً للمستقبل.</p><div className="labcards"><div><small>حالة السوق</small><strong>{regime?.label||'غير محسوم'}</strong><span>{regime?regime.confidence+'% ثقة تصنيف':'بانتظار البيانات'}</span></div><div><small>Paper Trading</small><strong>{paper?'يعمل':'متوقف'}</strong><span>{trades.some(t=>t.status==='open')?'صفقة افتراضية مفتوحة':'لا صفقة مفتوحة'}</span></div><div><small>Trade Journal</small><strong>{journalMode}</strong><span>{stats.closed} صفقة مغلقة · {stats.closed?num(stats.net,2)+'R':'لا نتائج بعد'}</span></div></div></section>
    <div className="grid"><section className="panel"><div className="panelhead"><h3>Forward Test · Paper</h3><Database size={19}/></div><p className="muted">أي إشارة مكتملة تُسجل افتراضياً دون إرسال أمر إلى MT5. عند توفر D1 يبقى السجل على الخادم؛ وإلا يعمل fallback بدون تعطيل النظام.</p><button className="primary" onClick={toggle}>{paper?'إيقاف Paper Trading':'تشغيل Paper Trading'}</button><div className="labstats"><span>Wins <b>{stats.wins}</b></span><span>Losses <b>{stats.losses}</b></span><span>Win Rate <b>{num(stats.winRate,1)}%</b></span><span>Net <b>{num(stats.net,2)}R</b></span></div>{trades.slice(0,6).map(t=><article className="papertrade" key={t.id}><div><strong>{t.mode==='news'?'NEWS · ':''}{t.side==='buy'?'BUY':'SELL'} · {t.score}/100</strong><small>{dt(t.openedAt)} · {t.eventName?`${t.eventName} · `:''}{t.regime}</small></div><span className={t.status==='open'?'tag':(t.resultR||0)>0?'connected':'offline'}>{t.status==='open'?'OPEN':`${(t.resultR||0)>0?'+':''}${num(t.resultR,2)}R`}</span></article>)}{trades.length>0&&<button className="textbutton dangerlink" onClick={()=>{save([]);try{localStorage.removeItem('gold-paper-trades');}catch{}}}><Trash2 size={15}/> مسح العرض المحلي</button>}</section>
    <section className="panel"><div className="panelhead"><h3>Backtest Pro + Walk‑Forward</h3><Play size={19}/></div><p className="muted">يجلب عدة دفعات M5 تاريخية من Binance XAUUSDT proxy، يعيد بناء M15/H1، ويضيف Spread/Slippage افتراضيين. Walk‑Forward يختار الإعدادات على الماضي ثم يختبرها على فترة لاحقة منفصلة. هذا الاختبار خاص بالاستراتيجية الفنية العادية؛ NEWS MODE يُقاس حاليًا بالـPaper/Journal إلى أن نربط أرشيف أخبار تاريخي متزامن مع M1.</p><button className="primary" onClick={runBacktest} disabled={busy}>{busy?'جارٍ جلب التاريخ والاختبار...':'تشغيل Backtest Pro'}</button>{error&&<p className="warning">{error}</p>}{backtest&&<><div className="labstats big"><span>Trades <b>{backtest.result.trades}</b></span><span>Win Rate <b>{num(backtest.result.winRate,1)}%</b></span><span>Profit Factor <b>{backtest.result.profitFactor==null?'—':num(backtest.result.profitFactor,2)}</b></span><span>Expectancy <b>{num(backtest.result.expectancyR,3)}R</b></span><span>Net <b>{num(backtest.result.netR,2)}R</b></span><span>Max DD <b>{num(backtest.result.maxDrawdownR,2)}R</b></span></div><p className="muted">التاريخ: {dt(backtest.history.from)} → {dt(backtest.history.to)} · {backtest.history.candles} شمعة · Spread ${num(backtest.costs.spreadUsd)} + Slippage ${num(backtest.costs.slippageUsd)}</p><h3>Out‑of‑Sample / Walk‑Forward</h3><div className="labstats big"><span>Stability <b>{backtest.walkForward.stabilityScore}/100</b></span><span>OOS Trades <b>{backtest.walkForward.outOfSampleTrades}</b></span><span>OOS Win <b>{num(backtest.walkForward.outOfSampleWinRate,1)}%</b></span><span>OOS PF <b>{backtest.walkForward.outOfSampleProfitFactor==null?'—':num(backtest.walkForward.outOfSampleProfitFactor,2)}</b></span><span>OOS Exp <b>{num(backtest.walkForward.outOfSampleExpectancyR,3)}R</b></span><span>Positive folds <b>{backtest.walkForward.positiveFolds}/{backtest.walkForward.folds.length}</b></span></div>{backtest.walkForward.folds.map((f,i)=><article className="papertrade" key={i}><div><strong>Fold {i+1} · Score {f.selectedRules.minScore} · ADX {f.selectedRules.adx}</strong><small>Test {dt(f.testFrom)} → {dt(f.testTo)}</small></div><span className={f.test.netR>0?'connected':'offline'}>{f.test.netR>0?'+':''}{num(f.test.netR,2)}R</span></article>)}{[...backtest.result.assumptions,...backtest.walkForward.notes].map(x=><div className="rule compact" key={x}><TriangleAlert/>{x}</div>)}</>}</section></div>
    <div className="grid"><section className="panel"><div className="panelhead"><h3>Risk Engine</h3><ShieldCheck size={19}/></div><div className="rule compact"><ShieldCheck/>مخاطرة الصفقة محدودة محلياً في جسر MT5، ولا يمكن تجاوز حدودها من الواجهة.</div><div className="rule compact"><ShieldCheck/>Daily + Weekly loss limits، Drawdown، خسائر متتالية، وMargin Level.</div><div className="rule compact"><ShieldCheck/>Kill Switch، منع تكرار الإشارة، Cooldown وصفقة واحدة افتراضياً.</div></section><section className="panel"><div className="panelhead"><h3>Execution Quality Monitor</h3><Activity size={19}/></div><div className="rule compact"><ShieldCheck/>MT5 Tick الحديث يصبح مصدر السعر الأساسي قبل التنفيذ.</div><div className="rule compact"><ShieldCheck/>رفض Tick قديم أو إشارة منتهية وقياس فرق سعر الإشارة عن الوسيط.</div><div className="rule compact"><ShieldCheck/>قياس order_check / order_send وتسجيل جودة التنفيذ في الجسر.</div></section></div>
  </>;
}
